url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Critical Theory in the Global South" # the name of your site, e.g. ACME Corp.

navigation:
  - label: About
    url: /about/
  - label: Resources
    url: /resources/

collections:
  resources:
    output: true
    layout: item
    permalink: /:collection/:title/


defaults:
  - scope:
      path: ""
      type: "resources"
    values:
      layout: "item"
